version: '3'

# xhost +

services:
    deepstream:
      build: .
      tty: true
      runtime: nvidia
      environment:
        NVIDIA_VISIBLE_DEVICES: all
        DISPLAY: ${DISPLAY}
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ../../deepstream-occupancy-analytics:/opt/nvidia/deepstream/deepstream-5.0/sources/apps/sample_apps/deepstream-occupancy-analytics
        - ../sample:/sample_mov
    zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"
    kafka:
      build: 
        context: ./kafka-docker
        dockerfile: Dockerfile
      ports:
        - "9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 192.168.1.22
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
